version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx_teszt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /home/attila/dteszt/Munka:/config
    ports:
      - 8080:80
      # - 443:443
    restart: unless-stopped